### ISSUE TITLE
Uncontrollable page opening

### ISSUE THREAD

**Issue by KarelWintersky** [matt-kruse/old-layout#3]
Today, your page 
https://oldlayout.com/update.html?version=3.0

opened without any permissions from user or browser.

*Don't do this anymore*

Very. BAD. practice.

**Comment by matt-kruse** [comment]
This is actually a very normal practice for extensions, to inform users of changes.

**Comment by KarelWintersky** [comment]
Nope. Use popup. Not an opening page with loosing current focus.

**Comment by krzysztof-sikorski** [comment]
> This is actually a very normal practice for extensions, to inform users of changes.

Some users like to know what has changed. Some users do not care and want the software to "just work". One of those groups will always be displeased by whatever the author chooses.

The best solution I have seen in such cases is to make the behaviour customisable, although this can still provoke a heated discussion about what should be the default setting.

**Comment by matt-kruse** [comment]
Since I'm the author of this and I've spent many hours of my life dedicated to making it work for hundreds of thousands of people, I don't think it's too much of an inconvenience for users to see a simple message when it updates. Everyone is free to ignore it or even uninstall if they really find it so offensive. I think it's too much to ask for a software developer to invest their time into creating a product you like, to solve a problem you have, at no cost to you, and then be demanding about how they choose to communicate back to you about updates and improvements they've made. Software developers are not your slaves. :)

**Comment by dmitriy1980** [comment]
I'd say there's no way to please every single person on the planet. For that, there are standards and best practices. I totally agree with Matt in that the industry standard for release notes is to open up a new browser window/tab that provides release notes for the latest version of software.

**Comment by KarelWintersky** [comment]
Best practice is: do **not** distract the user by opening a new window/tab at any (or update) action. 

I worked at my google doc, but 'update tab' opened without any notification.

WTF?? What is a distracting addon does it?? 
I typing in google doc, but browser switched window focus to... WTF??? 

And, I also creating products for **my** users. And, I think about better UX. Without annoyng popups

**Comment by krzysztof-sikorski** [comment]
I am sorry if I sounded offensive, I just wanted to point that whatever approach the author chooses, they will always be people displeased with the decisions. I do think making the behaviour customizable would partially please the crowd, but that is additional developer work so I completely understand if the author does not want to do that or simply do not have enough free time to do it.

**Comment by KarelWintersky** [comment]
> to solve a problem you have, at no cost to you

@matt-kruse , you need monetary support to solve **this** problem?
